### ISSUE TITLE
Update Issue

### ISSUE THREAD

**Issue by pflores429** [deadc0de6/catcli#20]
Seeing the following error when running an Update:
OSError: [WinError 4393] The tag present in the reparse point buffer is invalid:

Are there files that can cause this error that I should avoid?

**Comment by deadc0de6** [comment]
This sounds like a corrupted file is being accessed, googling `The tag present in the reparse point buffer is invalid` seems to lead to some onedrive bug.

I'd like to improve the way the error is reported but I would need more info from you in order to do this:

* Does catcli crash? What is the return code?
* Do you get any stacktrace?
* Could you try to update with the debug flag on (`--verbose`) and paste any relevant output here?

Thanks!

**Comment by pflores429** [comment]
Update for Issue 21 appears to have resolved this issue as well!
