### ISSUE TITLE
Usage in Data Lake

### ISSUE THREAD

**Issue by PAFlores** [deadc0de6/catcli#27]
We are going to use catcli to help manage the use of data lake  contents ("time traveling").  The question has come up as to where is the best place for the catcli.cataog file to reside, inside or outside of the data lake?

**Comment by deadc0de6** [comment]
That's a nice use of catcli, I'd be interested to see the perf of indexing a large data lake. 

If you keep the catalog within one of the directory you're indexing, obviously the value for itself (size, checksum, etc) but also of its parent hierarchy won't be accurate (since the file is written after indexing). But that's about the only drawback I see of having it inside in my opinion.

Then it all depends if you index the entire data lake at once (single storage) or as multiple storage, in which case you could put the catalog at the root and thus avoid indexing it.
