### ISSUE TITLE
ls for files, du

### ISSUE THREAD

**Issue by weberjn** [deadc0de6/catcli#42]
Not really an issue, but my impressions when trying out catcli. I do like catcli enough to bother to write this:

* was surprised that you cannot ls files:
```
(catcli) weberjn:~$ catcli ls tmptest/a
 +-+-+-+-+-+-+
 |c|a|t|c|l|i|
 +-+-+-+-+-+-+ v0.9.6

a [nbfiles:3, totsize:72]
- 1 [size:24]
- 2 [size:24]
- 3 [size:24]
(catcli) weberjn:~$ catcli ls tmptest/a/1
 +-+-+-+-+-+-+
 |c|a|t|c|l|i|
 +-+-+-+-+-+-+ v0.9.6

"tmptest/a/1": nothing found
```
* find should show the location, 'd like to see /etc/fstab here
```
(catcli) weberjn:~$ catcli -B find fstab
fstab [size:902, storage:etc]
```
* find and ls should support wildcards as in shell
```
catcli -B find '*.conf'
```
(catcli find conf also finds containers/registries.conf.d)

* I'd prefer if catcli would create in ~/.catcli a separate catalog file for each index, instead of asking to Update catalog.
```Update catalog "catcli.catalog" [y|N] ?```
Why do you ask that, isn't that natural to update the catalog?

* miss a du, e.g 
  ```catcli du -h tmptest/a```

* catcli without parameters should go into interactive mode and accept commands like ls, ..   (as ftp does)

**Comment by deadc0de6** [comment]
Thanks for your inputs. Here are a few answers/questions regarding your different points:

* (1) what would you expect a `ls` on a file to output?
* (2) I could add the full location when using `find` of course
* (3) adding wildcards support for `find` and `ls` is also doable
* (4) regarding the catalog, my use-case is mostly using the same catalog for everything I index in order to have everything in the same catalog (only one file to save/sync/backup and one single entry to have/find everything). However I could understand you'd like to have multiple catalog, isn't the `--catalog` cli switch enough?
* (5) implementing a `du` like would also be doable
* (6) an interactive mode is also something I could add

All those new features are doable and if you need them I would open a new issue for each of them and work on that. For my own curiosity, for what purpose are you using catcli?

**Comment by weberjn** [comment]
>    (1) what would you expect a ls on a file to output?

the output of ls -l

```ls -l /etc/fstab
-rw-r--r--  1 root wheel 262 Oct 14 15:11 /etc/fstab
```
At least date and location.

An ls and a -l option for that would be nice.

>   (4) regarding the catalog, my use-case is mostly using the same catalog for everything I index in order to have everything in the same catalog (only one file to save/sync/backup and one single entry to have/find everything). However I could understand you'd like to have multiple catalog, isn't the --catalog cli switch enough?

Actually the default catalog is ok, I was just puzzled that I was asked if it should be overwritten.

I wonder if individual catalog files would be faster, but you'd know that better.

> For my own curiosity, for what purpose are you using catcli?

Index my external USB drives.

**Comment by deadc0de6** [comment]
Thanks for all your inputs. I have added a few new features (and fixed some things too) in the branch [features-42](https://github.com/deadc0de6/catcli/tree/features-42). 

Besides the issues #43, #44 and #46, it will

* sort files like `ls` does
* `ls` and `find` now support wildcards
* provides an interactive mode (when no command is provided)
* adds a `tree` command (alias to `ls -r`)
